#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath "$0"))

cd $SCRIPT_DIR

source .install.sh

if [[ -z $RUN_WITH_COVERAGE ]]; then
	python3 .smartlocate.py $*
else
	coverage run .smartlocate.py $*
fi

exit $?
