#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

SCRIPT_DIR=$(dirname $(realpath "$0"))

cd $SCRIPT_DIR

cd ..

FINAL_EXIT_CODE=0

function run_and_fail {
	name=$1
	code=$2
	wanted_exit_code=$3

	echo -e "${YELLOW}Running $name${NC}"

	eval "$code"

	exit_code=$?

	if [[ $exit_code -ne $wanted_exit_code ]]; then
		echo -e "${RED}Failed: $code got $exit_code, wanted exit-code $wanted_exit_code${NC}"
		FINAL_EXIT_CODE=1
	fi
}

run_and_fail "Bash-Syntax-Check" "bash -n smartlocate" 0

run_and_fail "Compiling main script" "python3 -m py_compile .smartlocate.py" 0

run_and_fail "Main-script without parameters" "bash smartlocate" 0

run_and_fail "Indexing" "bash smartlocate --index --dir $(pwd)" 0


exit $FINAL_EXIT_CODE
