#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR

cd ..

source .install.sh

exit_code=0

if command -v mypy 2>/dev/null >/dev/null; then
	if [[ -z $1 ]]; then
		mypy --install-types --check-untyped-defs --ignore-missing-imports --disallow-untyped-defs .*.py
		exit_code=$?
	else
		mypy --install-types --check-untyped-defs --ignore-missing-imports --disallow-untyped-defs $*
		exit_code=$?
	fi
else
	echo "Warning: mypy is not installed. Cannot run mypy"
fi

exit $exit_code
